/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirst;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;


/**
 *
 * @author vansh
 */
class mymodel2 extends javax.swing.table.AbstractTableModel 
{
    ResultSet rs;
    ResultSetMetaData rsmd;
    mymodel2(ResultSet rs1)
    {
    try
    {
        rs=rs1;
        rsmd=rs.getMetaData();
    }
    catch(Exception e)
    {
        System.out.print(e);
    }
    }
    @Override
    public int getRowCount() {
       try
        {
            rs.last();
            return rs.getRow();
        }
        catch(Exception e)
        {
            System.out.print(e);
            return -1;
        }
    }

    @Override
    public int getColumnCount() {
         try
        {
           
            return rsmd.getColumnCount();
        }
        catch(Exception e)
        {
            System.out.print(e);
            return -1;
        }
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
    try{
        rs.absolute(rowIndex+1);
        return rs.getObject(columnIndex+1);
    } 
    catch(Exception e)
    {
        return null;
    }
    }
    
     public String getColumnName(int n)
    {
        try  
        {
            return rsmd.getColumnName(n+1);
        }
        catch(Exception e)
        {
         System.out.print(e);   
        return null;
        }
    }

}
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        super("ADMIN's WINDOW");
        initComponents();
        this.setBounds(600,150,750,700); 
        l1.setVisible(false);
        l2.setVisible(false);
        t1.setVisible(false);
        t2.setVisible(false);
        t4.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        l3.setVisible(false);
        t3.setVisible(false);
        l4.setVisible(false);
        b5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        b1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME ADMIN!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 10, 239, 35);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 720, 2);

        jt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 210, 480, 190);

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setText("VIEW EMPLOYEES");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(50, 250, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/panos-pizza.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(116, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(116, 100));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 60, 110, 100);
        getContentPane().add(t2);
        t2.setBounds(290, 480, 190, 40);
        getContentPane().add(t1);
        t1.setBounds(70, 480, 190, 40);

        l2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("PASSWORD: ");
        getContentPane().add(l2);
        l2.setBounds(290, 450, 190, 30);

        l1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("NAME :");
        getContentPane().add(l1);
        l1.setBounds(70, 450, 190, 30);

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setText("DELETE");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(500, 580, 130, 40);

        l4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        l4.setText("ID:");
        getContentPane().add(l4);
        l4.setBounds(20, 80, 20, 20);

        t3.setEditable(false);
        getContentPane().add(t3);
        t3.setBounds(40, 80, 40, 22);
        getContentPane().add(t4);
        t4.setBounds(510, 480, 190, 40);

        l3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("CONTACT NO. :");
        getContentPane().add(l3);
        l3.setBounds(510, 450, 190, 30);

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setText("UPDATE");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(170, 580, 130, 40);

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setText("ADD EMPLOYEE");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(50, 330, 140, 40);

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/save.png"))); // NOI18N
        b5.setText("ADD DATA");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(330, 580, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
       Class.forName("com.mysql.jdbc.Driver");
       Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
             Statement st=c.createStatement();
             ResultSet rs=st.executeQuery("select * from data");
           mymodel2 m1=new mymodel2(rs);
           jt1.setModel(m1);
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void jt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt1MouseClicked
        // TODO add your handling code here:
        l1.setVisible(true);
        l2.setVisible(true);
        t1.setVisible(true);
        t2.setVisible(true);
        b2.setVisible(true);
        b3.setVisible(true);
        t4.setVisible(true);
        l3.setVisible(true);
        l4.setVisible(true);
        t3.setVisible(true);
        TableModel m = jt1.getModel();
        String NAME = m.getValueAt(jt1.getSelectedRow(), 1).toString();
        t1.setText(NAME);
        String contact = m.getValueAt(jt1.getSelectedRow(), 3).toString();
        t4.setText(contact);
        String ID =  m.getValueAt(jt1.getSelectedRow(), 0).toString();
        t3.setText(ID);
        String password = m.getValueAt(jt1.getSelectedRow(), 2).toString();
        t2.setText(password);
    }//GEN-LAST:event_jt1MouseClicked

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
       
       try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
            Statement st=c.createStatement();

            int i = st.executeUpdate("update data set NAME = '"+t1.getText()+"', PASSWORD = '"+t2.getText()+"', CONTACT = '"+t4.getText()+"' where ID = '"+t3.getText()+"'");
            if(i==1)
            {
                JOptionPane.showMessageDialog(this, "DATA UPDATED!!");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
            // T1.setText("101");
        }
       try
        {
       Class.forName("com.mysql.jdbc.Driver");
       Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
             Statement st=c.createStatement();
             ResultSet rs=st.executeQuery("select * from data");
           mymodel2 m1=new mymodel2(rs);
           jt1.setModel(m1);
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        t3.setVisible(true);
        l4.setVisible(true);
        try
        {
       Class.forName("com.mysql.jdbc.Driver");
       Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
             Statement st=c.createStatement();
             ResultSet rs=st.executeQuery("select max(ID) from data");
           if(rs.next()){
           int i = Integer.parseInt(rs.getString(1));
           i = i+1;
           t3.setText("" + i);
           }
        }
        catch(Exception e)
        {
           // System.out.print(e);
            t3.setText("1");
        }
        
        l1.setVisible(true);
        l2.setVisible(true);
        t1.setVisible(true);
        t2.setVisible(true);
        t4.setVisible(true);
        l3.setVisible(true);
        b5.setVisible(true);
       
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
            Statement st=c.createStatement();

            int i = st.executeUpdate("insert into data values ('"+t3.getText()+"', '"+t1.getText()+"', '"+t2.getText()+"', '"+t4.getText()+"')");
            if(i==1)
            {
               
                JOptionPane.showMessageDialog(this, "NEW EMPLOYEE ADDED!!");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
            // T1.setText("101");
        }
         try
        {
       Class.forName("com.mysql.jdbc.Driver");
       Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
             Statement st=c.createStatement();
             ResultSet rs=st.executeQuery("select * from data");
           mymodel2 m1=new mymodel2(rs);
           jt1.setModel(m1);
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
         
    }//GEN-LAST:event_b5ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
            Statement st=c.createStatement();

            int i = st.executeUpdate("delete from data where ID = '"+t3.getText()+"'");
            if(i==1)
            {
                JOptionPane.showMessageDialog(this, "DATA DELETED!!");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
            // T1.setText("101");
        }
        try
        {
       Class.forName("com.mysql.jdbc.Driver");
       Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
             Statement st=c.createStatement();
             ResultSet rs=st.executeQuery("select * from data");
           mymodel2 m1=new mymodel2(rs);
           jt1.setModel(m1);
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_b3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jt1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
