/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirst;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author vanshaj
 */
           
class mymodel extends javax.swing.table.AbstractTableModel 
{
    ResultSet rs;
    ResultSetMetaData rsmd;
    mymodel(ResultSet rs1)
    {
    try
    {
        rs=rs1;
        rsmd=rs.getMetaData();
    }
    catch(Exception e)
    {
        System.out.print(e);
    }
    }
    @Override
    public int getRowCount() {
       try
        {
            rs.last();
            return rs.getRow();
        }
        catch(Exception e)
        {
            System.out.print(e);
            return -1;
        }
    }

    @Override
    public int getColumnCount() {
         try
        {
           
            return rsmd.getColumnCount();
        }
        catch(Exception e)
        {
            System.out.print(e);
            return -1;
        }
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
    try{
        rs.absolute(rowIndex+1);
        return rs.getObject(columnIndex+1);
    } 
    catch(Exception e)
    {
        return null;
    }
    }
    
     public String getColumnName(int n)
    {
        try  
        {
            return rsmd.getColumnName(n+1);
        }
        catch(Exception e)
        {
         System.out.print(e);   
        return null;
        }
    }

}


public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        this.setBounds(500,100,1000,800);
     
         try
        {
       Class.forName("com.mysql.jdbc.Driver");
       Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizza","root","");
             Statement st=c.createStatement();
             ResultSet rs=st.executeQuery("select * from pizza");
           mymodel m1=new mymodel(rs);
           jt2.setModel(m1);
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
         
         
         try
        { 
            double i = 0.00;
            double j;
            double k = 0.00;
            double t = 0.00;
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizza","root","");
            PreparedStatement st=c.prepareStatement("select Cost from pizza");
            ResultSet rs=st.executeQuery();
           while(rs.next()){
              j = Double.parseDouble(rs.getString("Cost"));
           i = i + j;
           T5.setText("" + i);
           k = k + 0.04*j;
           T6.setText("" + k);
           t = i + k;
           T7.setText("" + t);
           }
            c.close();
            st.close();
            rs.close();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BILLING");
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/panos_pizza_100x100.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 10, 100, 90);

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 240, 1010, 2);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel3.setText("CONTACT NO. :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 320, 110, 30);

        T4.setEditable(false);
        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        getContentPane().add(T4);
        T4.setBounds(670, 320, 230, 30);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        jLabel4.setText("NAME:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 320, 60, 30);

        T3.setEditable(false);
        getContentPane().add(T3);
        T3.setBounds(150, 320, 230, 30);

        jt2.setBackground(new java.awt.Color(204, 204, 204));
        jt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jt2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 400, 1000, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PRICE DETAILS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sub Total:");

        T5.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GST:");

        T6.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Grand Total:");

        T7.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(640, 530, 310, 190);

        T1.setText("ENTER YOUR CONTACT NUMBER:");
        T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T1MouseClicked(evt);
            }
        });
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        getContentPane().add(T1);
        T1.setBounds(20, 182, 210, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 180, 110, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PRINT RECEIPT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(371, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 240, 1010, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
        
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("ORDER DETAILS.pdf"));
            document.open();
            
            document.addTitle("Order Details");
            document.addAuthor("Vanshaj Pahwa");
            document.addCreator("Vanshaj Pahwa");
            
            String img = "C:\\Users\\vansh\\OneDrive\\Documents\\NetBeansProjects\\myfirst\\src\\myfirst\\panos_pizza_100x100.png";
            Image img1 = Image.getInstance(img);
            img1.scaleAbsolute(80, 80);
            img1.setAlignment(Element.ALIGN_CENTER);
            document.add(img1);
            Paragraph paragraph = new Paragraph(" " + new java.util.Date());
            paragraph.setAlignment(Element.ALIGN_CENTER);
            document.add(paragraph);
            paragraph = new Paragraph("\n \n \n");
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph("NAME: " + " " + T3.getText());
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph("CONTACT: " + " " + T4.getText());
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
            paragraph = new Paragraph("\n \n");
            paragraph.setAlignment(Element.ALIGN_LEFT);
            document.add(paragraph);
        
            paragraph = new Paragraph("--------------------------------------ORDER DETAILS-------------------------------------------\n \n ");
            paragraph.setAlignment(Element.ALIGN_CENTER);
            document.add(paragraph);
            
           PdfPTable table=new PdfPTable(7);
            try
            {
               Class.forName("com.mysql.jdbc.Driver");
               Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizza","root","");
               Statement st=c.createStatement();
               ResultSet rs=st.executeQuery("select * from pizza");
               PdfPCell c2= new PdfPCell(new Phrase("ID"));
               table.addCell(c2);
               c2= new PdfPCell(new Phrase("NAME"));
               table.addCell(c2);
               c2= new PdfPCell(new Phrase("TYPE"));
               table.addCell(c2);
               c2= new PdfPCell(new Phrase("CUSTOMISATION"));
               table.addCell(c2);
               c2= new PdfPCell(new Phrase("SIZE"));
               table.addCell(c2);
               c2= new PdfPCell(new Phrase("QUANTITY"));
               table.addCell(c2);
               c2= new PdfPCell(new Phrase("COST"));
               table.addCell(c2);
               while(rs.next()){
                 String ID = rs.getString("ID");
                  PdfPCell c1= new PdfPCell(new Phrase(ID));
                  table.addCell(c1);
                  String Name = rs.getString("NAME");
                  c1= new PdfPCell(new Phrase(Name));
                  table.addCell(c1);
                  String Type = rs.getString("TYPE");
                  c1= new PdfPCell(new Phrase(Type));
                  table.addCell(c1);
                  String C = rs.getString("CUSTOMISATION");
                  c1= new PdfPCell(new Phrase(C));
                  table.addCell(c1);
                  String Size = rs.getString("SIZE");
                  c1= new PdfPCell(new Phrase(Size));
                  table.addCell(c1);
                  String Q = rs.getString("QUANTITY");
                  c1= new PdfPCell(new Phrase(Q));
                  table.addCell(c1);
                  String P = rs.getString("COST");
                  c1= new PdfPCell(new Phrase(P));
                  table.addCell(c1);
                  document.add(table); 
               }
               paragraph = new Paragraph("\n \n \n--------------------------------------------PRICE DETAILS--------------------------------------------\n \n");
               paragraph.setAlignment(Element.ALIGN_CENTER);
               document.add(paragraph);
            paragraph = new Paragraph("Sub Total: " + " " + T5.getText());
            paragraph.setAlignment(Element.ALIGN_RIGHT);
            document.add(paragraph);
            paragraph = new Paragraph("GST: " + " " + T6.getText());
            paragraph.setAlignment(Element.ALIGN_RIGHT);
            document.add(paragraph);
             paragraph = new Paragraph("Grand Total: " + " " + T7.getText());
            paragraph.setAlignment(Element.ALIGN_RIGHT);
            document.add(paragraph);
               //document.add(table);
            }
        catch(Exception e)
        {
            System.out.print(e);
        }
            document.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        
      try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizza","root","");
            Statement st=c.createStatement();

           int i = st.executeUpdate("DELETE from pizza");
            if(i==1)
            {
                JOptionPane.showMessageDialog(this, "ORDER PLACED!!");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
            // T1.setText("101");
        } 
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void T1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T1MouseClicked
        // TODO add your handling code here:
        T1.setText("");
    }//GEN-LAST:event_T1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/customer","root","");
            Statement st=c.createStatement();
            ResultSet rs = st.executeQuery("Select NAME, CONTACT from customer where CONTACT ='"+T1.getText()+"'");
            if(rs.next())
            {
                String NAME = rs.getString("NAME");
                T3.setText("" + NAME);
                String CONTACT = rs.getString("CONTACT");
                T4.setText("" + CONTACT);
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
            // T1.setText("101");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jt2;
    // End of variables declaration//GEN-END:variables
}
