/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myfirst;

/**
 *
 * @author vansh
 */
public class NonVeg extends javax.swing.JInternalFrame {

    /** Creates new form NonVeg */
    public NonVeg() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/Barbecue.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 30, 120, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/Chicken c.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 250, 120, 120);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("PEPPER BARBECUE CHICKEN");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 170, 210, 19);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("CHICKEN MARGHERITA");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 170, 177, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/peri peri.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 30, 120, 120);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("CHICKEN GOLDEN CORN");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 370, 184, 19);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/Chicken gc.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 240, 120, 120);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("PERI PERI CHICKEN");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(140, 380, 144, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
