/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirst;

import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author vansh
 */
public class Welcome extends javax.swing.JFrame{

    /**
     * Creates new form Welcome
     */
    
    public Welcome() {
        initComponents();
        this.setBounds(600,150,790,835);
        
     P2.setVisible(false);
     Pf1.setVisible(false);
     L1.setVisible(false);
     
      
        jButton2.setVisible(false); 
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
            Statement st=c.createStatement();
            ResultSet rs=st.executeQuery("select Name from data");
            while(rs.next()){
                C1.addItem(rs.getString("Name"));
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        C1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Pf1 = new javax.swing.JPasswordField();
        L1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Pano's Pizza");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(26, 13, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/panos-pizza.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 10, 120, 90);

        jLabel3.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Here to make you happy");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 210, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 10, 210, 170);

        P2.setBackground(new java.awt.Color(26, 13, 0));
        P2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        P2.setLayout(null);

        C1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT ADMIN" }));
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        P2.add(C1);
        C1.setBounds(60, 20, 200, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/login.png"))); // NOI18N
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        P2.add(jButton2);
        jButton2.setBounds(90, 180, 130, 40);
        P2.add(Pf1);
        Pf1.setBounds(60, 120, 200, 40);

        L1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 255, 255));
        L1.setText("ENTER YOUR PASSWORD:");
        P2.add(L1);
        L1.setBounds(70, 90, 200, 30);

        getContentPane().add(P2);
        P2.setBounds(240, 420, 330, 230);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setText("ADMIN LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 360, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/pizza1_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 740);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, null, null));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(144, 45));

        jMenu1.setBackground(new java.awt.Color(255, 255, 204));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/Menu.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenu3.setText("Pizza");

        jMenuItem1.setText("View Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setText("Order Now");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/cart.png"))); // NOI18N
        jMenu2.setText("Cart");

        jMenuItem2.setText("View Cart");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        P2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        L1.setVisible(true);
        Pf1.setVisible(true);
        jButton2.setVisible(true);
    }//GEN-LAST:event_C1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String name = C1.getSelectedItem().toString();
        String pass = new String(Pf1.getPassword());
       
      try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/admin","root","");
            PreparedStatement st=c.prepareStatement("select * from data where NAME='"+name+"' and PASSWORD='"+pass+"'");
            ResultSet rs=st.executeQuery();
           if(rs.next()){
               JOptionPane.showMessageDialog(this, "LOGGED IN SUCCESSFULLY!!");
               Admin A1 = new Admin();
               A1.setVisible(true);
           }
           else{
              JOptionPane.showMessageDialog(this, "Please Enter A Valid Username Or Password.");
           }
            c.close();
            st.close();
            rs.close();
        }
        catch(Exception e)
        {
            System.out.print(e);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Login L1 = new Login();
        L1.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Menu m1 = new Menu();
        m1.setVisible(true);
        m1.setSize(816,830);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Billing B1 = new Billing();
        B1.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> C1;
    private javax.swing.JLabel L1;
    private javax.swing.JPanel P2;
    private javax.swing.JPasswordField Pf1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
